#PRIMERO CREA LA BASE DE DATOS Y DESPUES CORRE ESTE SQL EN MYSQL, YA ESTA ADAPTADA PARA EL 

CREATE TABLE USUARIO (
  USU_ID INT AUTO_INCREMENT PRIMARY KEY,
  USU_NOMBRE VARCHAR(20) NOT NULL,
  USU_EMAIL VARCHAR(100) UNIQUE NOT NULL,
  USU_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIA (
  CAT_ID INT AUTO_INCREMENT PRIMARY KEY,
  CAT_NOMBRE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE JUEGO (
  JUE_ID INT AUTO_INCREMENT PRIMARY KEY,
  JUE_TITULO VARCHAR(100) NOT NULL,
  JUE_DESCRIPCION VARCHAR(200) NOT NULL,
  JUE_URL VARCHAR(500) NOT NULL,
  CAT_ID_JUEGO INT NOT NULL,
  FOREIGN KEY (CAT_ID_JUEGO) REFERENCES CATEGORIA(CAT_ID)
);

CREATE TABLE FAVORITO (
  FAV_ID INT AUTO_INCREMENT PRIMARY KEY,
  USU_ID_FAVORITO INT,
  JUE_ID_FAVORITO INT,
  FOREIGN KEY (USU_ID_FAVORITO) REFERENCES USUARIO(USU_ID),
  FOREIGN KEY (JUE_ID_FAVORITO) REFERENCES JUEGO(JUE_ID)
);

CREATE TABLE RECIENTE (
  REC_ID INT AUTO_INCREMENT PRIMARY KEY,
  USU_ID_RECIENTE INT,
  JUE_ID_RECIENTE INT,
  REC_FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USU_ID_RECIENTE) REFERENCES USUARIO(USU_ID),
  FOREIGN KEY (JUE_ID_RECIENTE) REFERENCES JUEGO(JUE_ID)
)
